### ISSUE TITLE
mate-screenshot fails when started with no option

### ISSUE THREAD

**Issue by denispr** [mate-desktop/mate-utils#97] opened 2015-04-20 19:54 UTC
While "mate-screenshot --interactive" works, "mate-screenshot" (which is started by the Printscreen key) fails with a dialog box saying "UI definition file for the screenshot program is missing.
Please check your installation of mate-utils".
This is with mate-utils 1.8.1+dfsg1-2 on a Debian Jessie system.

**Comment by monsta** [comment] 2015-04-22 11:03
Can't reproduce it. Try reinstalling ```mate-utils``` and ```mate-utils-common``` packages.

**Comment by denispr** [comment] 2015-04-22 12:48
I tried apt-get remove mate-utils mate-utils-common
then apt-get install mate-utils mate-utils-common
then reboot, just in case, but the problem is still there. Strange...
Is there anything I could check ?

**Comment by monsta** [comment] 2015-04-22 13:05
Ah, I remember the related issue. It always says that UI file is missing, even if it's there and some other problem happened. So it might be any other error.
I've fixed that in https://github.com/mate-desktop/mate-utils/commit/f42b01a0732dc8f9b6c73e44e43fc1badb9b0565 but that commit didn't make it to 1.8.
If you know how to rebuild packages, you can cherry-pick that commit into Jessie. In the meanwhile, I'll ask the maintainers if we could get it there officially (which is not easy due to Jessie being near release).

**Comment by monsta** [comment] 2015-04-22 14:37
Try this simple script:

```
#!/usr/bin/python

import gtk

builder = gtk.Builder()
builder.add_from_file("/usr/share/mate-screenshot/mate-screenshot.ui")
```
It should show you the error message on loading the UI file.

**Comment by denispr** [comment] 2015-04-22 15:52
Sorry for my ignorance, but I don't understand exactly what I should do.
Should I run that script, then run "mate-screenshot" ?
Where is supposed to be shown the error message ?
Thanks,

**Comment by monsta** [comment] 2015-04-22 17:29
Just save the script, make it executable (```chmod +x script_name```) and run it in the terminal.
It should fail and show the error message.
No need to run mate-screenshot - this script simply tries to reproduce what happens in mate-screenshot. :)

**Comment by denispr** [comment] 2015-04-22 19:01
OK, I tried that : the script does not show any error message in the terminal, while mate-screenshot started from the terminal goes on showing a dialog box that says "UI definition file for the screenshot program is missing. Please check your installation of mate-utils".

**Comment by monsta** [comment] 2015-04-23 07:26
That sucks... Ok, I've filed [bug report](https://bugs.debian.org/783162) to Debian bug tracker, let's hope it will be fixed in Jessie.

**Comment by denispr** [comment] 2015-04-24 06:05
Thanks

**Comment by monsta** [comment] 2015-06-10 06:31
Ok, the updated version of mate-utils is now in Jessie.
Can you check what's the error message now?

**Comment by denispr** [comment] 2015-06-10 11:24
I've just updated my system with mate-utils 1.8.1+dfsg1-2+deb8u1.
Il still get the message "UI definition file for the screenshot program is missing.
Please check your installation of mate-utils" when starting mate-screenshot.

**Comment by monsta** [comment] 2015-06-10 11:52
That's strange, it should now say "Error loading UI definition file for the screenshot program: " and then the actual error message.

**Comment by denispr** [comment] 2015-06-10 12:34
Yes, that's strange, is the mate-utils version I'm using (1.8.1+dfsg1-2+deb8u1) the right one ?

**Comment by monsta** [comment] 2015-06-10 12:42
Yes, 1.8.1+dfsg1-2+deb8u1, for both mate-utils and mate-utils-common...

**Comment by denispr** [comment] 2015-06-10 12:54
mate-utils and mate-utils-common are both 1.8.1+dfsg1-2+deb8u1 on my system (LMDE Betsy based on Jessie)

**Comment by monsta** [comment] 2015-06-10 14:31
Maybe the bug will go away once Clem pushes 1.10 in Betsy repos :)

**Comment by denispr** [comment] 2015-06-10 15:17
Yes, I will let you know, that should happen soon...

**Comment by denispr** [comment] 2015-07-01 07:12
Unfortunately, still the same error message with mate-utils 1.10
"UI definition file for the screenshot program is missing.
Please check your installation of mate-utils"

**Comment by monsta** [comment] 2015-07-01 09:03
Weird...

**Comment by monsta** [comment] 2016-01-26 18:43
How's it going with 1.12?

**Comment by denispr** [comment] 2016-01-26 20:02
Fixed !

**Comment by monsta** [comment] 2016-01-26 20:03
Good :smile:

**Closed by monsta** 2016-01-26 20:03 UTC
Labels: unconfirmed
